### PR TITLE
Issue: 414 custom error message on port in use

### PR DESCRIPTION
**Pull request by barash-asenov**
Fixes https://github.com/LuteOrg/lute-v3/issues/414 by returning custom errors message in case of a used port.

### CODE REVIEW

**Comment by jzohrab** [comment]
Thank you very much @barash-asenov !  I'll try this out and hope to get it into the next release.  Appreciated 👍

**Review by jzohrab — APPROVED** [review]
LGTM 👍   I'll change "address :" to "port :" in the print message.

**Comment by barash-asenov** [comment]
> LGTM 👍 I'll change "address :" to "port :" in the print message.

Done

**Comment by jzohrab** [comment]
Thanks again @barash-asenov -- main changed a bit since you submitted this PR, so I'm rebasing this work to keep your commits, and tweaking the display of the message slightly:

```
  ERROR: port 5000 is already in use.
  please try adding a --port parameter, e.g.:
  
    python -m lute.main --port 9876
```

Nice work with the `OSError`, I wasn't aware of that and would have done it poorly. :-)

Closing this PR as I'll use the rebased branch.  Thank you again!

**Pull request closed without merging**
